version: '2'
services:
  web:
    #build: .
    image: 554456905959.dkr.ecr.us-east-1.amazonaws.com/electron-release-server
    environment:
      APP_USERNAME: airship
      APP_PASSWORD: Airship123!!
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: releaseserver
      DB_NAME: releaseserver
      DB_PASSWORD: secret
      TOKEN_SECRET: 48f399539008689c4fa46e115bd6a212
      APP_URL: 'http://54.157.75.69'
      NODE_ENV: 'production'
    depends_on:
      - db
    ports:
      - '80:80'
    entrypoint: ./scripts/wait.sh db:5432 -- npm start
  db:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: releaseserver
